### PR TITLE
Replace old changelog (CHANGES) by a new one (ChangeLog.md)

### PR DESCRIPTION
**Pull request by Fellypao**
Since some websites that track free (or non-free) software use their changelogs to get information about new releases (see [1] , for example), I guess that to keep a changelog up to date can help to increase SciDAVis visibility (and do not cost too much...).
In the proposed changelog (ChangeLog.md) I kept the existing information in the old SciDAVis changelog (CHANGES) and added, in most of cases, only information about versions and release dates - based on the dates on which the source codes were added to the SF site - that is more for historical reference. In the next releases more detailed information can be added.
My preference is to show the latest version first, but this can be changed if it is more convenient to have it in the inverse order.
I'm not sure if a markdown (.md) file is needed.

[1] https://www.opendesktop.org/p/1131769/

### CODE REVIEW

**Comment by highperformancecoder** [comment]
This information is in the git commit log. Can this not be automated somehow, if we really need such a file?

**Comment by Fellypao** [comment]
I believe this can be automated, but I do not know how. I also do not know if it is necessary to put all the git commit log information into the changelog.

**Comment by highperformancecoder** [comment]
On Mon, May 14, 2018 at 08:02:02AM -0700, Fellype do Nascimento wrote:
> I believe this can be automated, but I do not know how. I also do not know if it is necessary to put all the git commit log information into the changelog.
> 

A quick bit of googling suggests this:

> git log --no-merges --format=%B

Replace old changelog (CHANGES) by a new one (ChangeLog.md)

Release 1.22.2

Update reference images and data

Fix for implicit conversion of QString to char*

Improve handling of script output

Fix use of non-ASCII characters in scripts

Add python3 module initialization

...

If this is a suitable changelog format, then I'd suggest adding that
line to the makeRelease.sh script, which is run every time a SciDaVis
release is prepared. If it, or a variant is not suitable, then I'd
rather we didn't have a changelog file. I have never so much as looked
at a changelog file in nearly 40 years of computing, and I have no
idea what they're used for. But it is clear that we don't want to be
spending a lot of precious volunteer attention doing mere editing and
administrivia, particularly when that can be more productively be
spent on improving the manual :).

-- 

----------------------------------------------------------------------------
Dr Russell Standish                    Phone 0425 253119 (mobile)
Principal, High Performance Coders
Visiting Senior Research Fellow        hpcoder@hpcoders.com.au
Economics, Kingston University         http://www.hpcoders.com.au
----------------------------------------------------------------------------

**Comment by Fellypao** [comment]
> I have never so much as looked at a changelog file in nearly 40 years of computing, and I have no idea what they're used for. 

Well... I usually check the changelogs of software that I compile from source by myself, even if I use a script do to that. I do it because compilation is a time consuming task and by reading a chengelog first I can decide if an update is necessary or not.

There are a few ways to tell users, packagers, distro maintainers, etc..., what changes have been made in the software between one version and another: add a news section to the software page, send e-mails to lists, post on social networks, and others that I can not remember now :-) All them are more time consuming than to edit a changelog.
IMHO, a changelog is useful if it contains useful information. Particularly, I like the way that Jeremy Sanders do with Veusz: he writes a changelog that is shipped with source code and also publish those information as a release note (see [1] for the latest release notes for Veusz). By doing that, all users (people that build from source and the ones that download binaries) can know what changed between subsequent versions.

> But it is clear that we don't want to be spending a lot of precious volunteer attention doing mere editing and administrivia

IMHO, to add information to a chalgelog when we have nearly 2 releases per year isn't "a lot" of work. Even more if we mix automation+manual editing. That is: use 'git log --no-merges --format=%B' to generate a basic file, clean it manually and insert the relevant info in the changelog. I can do it without problems. Just let me know about a new release one week before :-)

Anyway, it is up to you to decide. 

Best regards.

[1] https://veusz.github.io/releasenotes/2.2.2.txt

**Comment by highperformancecoder** [comment]
On Tue, May 15, 2018 at 07:43:20AM -0700, Fellype do Nascimento wrote:
> > I have never so much as looked at a changelog file in nearly 40 years of computing, and I have no idea what they're used for. 
> 
> Well... I usually check the changelogs of software that I compile from source by myself, even if I use a script do to that. I do it because compilation is a time consuming task and by reading a chengelog first I can decide if an update is necessary or not.

Well, the only reason I'd be doing that is because of some bug that is
annoying me. One of the things I'd do before lodging a bug report is
to compile the software to check whether the bug has been fixed, and
I'd do that even if the commit log said it had been fixed.

Otherwise, I tended to upgrade at 18 month intervals to amortise the
pain, although now with Tumbleweed, the updates come at rather random
time without thinking about it (and with one exception, been
completely painless). Changelogs would not have helped with the one
exception either.

Yet I do remember consulting logs of changes when applying system
patches to SunOS (egads that dates me!). In that case, the
consequences of getting it wrong were dire (trashed machine, angry
users, ...), and there was no access to the commit log (it being
proprietry software). But I've never done it for open source :).

> 
> There are a few ways to tell users, packagers, distro maintainers, etc..., what changes have been made in the software between one version and another: add a news section to the software page, send e-mails to lists, post on social networks, and others that I can not remember now :-) All them are more time consuming than to edit a changelog.
> IMHO, a changelog is useful if it contains useful information. Particularly, I like the way that Jeremy Sanders do with Veusz: he writes a changelog that is shipped with source code and also publish those information as a release note (see [1] for the latest release notes for Veusz). By doing that, all users (people that build from source and the ones that download binaries) can know what changed between subsequent versions.
> 
> > But it is clear that we don't want to be spending a lot of precious volunteer attention doing mere editing and administrivia
> 
> IMHO, to add information to a chalgelog when we have nearly 2 releases per year isn't "a lot" of work. Even more if we mix automation+manual editing. That is: use 'git log --no-merges --format=%B' to generate a basic file, clean it manually and insert the relevant info in the changelog. I can do it without problems. Just let me know about a new release one week before :-)
>

Fair enough - I should actually do a "release candidate" (or
candidates if necessary) before the actual release to get you guys to
focus on such last minute things. That gives you a chance to update a
change log if you want.

> Anyway, it is up to you to decide. 
> 
> Best regards.
> 
> [1] https://veusz.github.io/releasenotes/2.2.2.txt
> 
> -- 
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub:
> https://github.com/highperformancecoder/scidavis/pull/76#issuecomment-389192695

-- 

----------------------------------------------------------------------------
Dr Russell Standish                    Phone 0425 253119 (mobile)
Principal, High Performance Coders
Visiting Senior Research Fellow        hpcoder@hpcoders.com.au
Economics, Kingston University         http://www.hpcoders.com.au
----------------------------------------------------------------------------

**Pull request merged**
