### PR TITLE
Add calculation and display of curve integral

### PR DESCRIPTION
**Pull request by gbm19**
This is a first attempt to implement feature request #100.

### CODE REVIEW

**Review by highperformancecoder — APPROVED** [review]
My main comment is that we should be adding RAII code for any new work to improve exception safety. In this case, a vector<double> might be a suitable replacement for new double[], and malloc below. If you are concerned about paying unneeded initialisation costs, there are ways of writing the code to avoid it, using reserve() and emplace_back(). Alternatively, use a roll-your-own container (eg ecolab::array) that does not initialise its members

I know scidavis is not currently exception safe, but we should aim for it ultimately.

**Comment by gbm19** [comment]
Please check attached patch to improve Integration::trapezoid().
Replacing 'new' and 'delete' in Filter::output() and others in Filter.cpp
would require rewriting all files that include Filter.h
[use-gsl-vectors-in-trapezoid.patch.txt](https://github.com/highperformancecoder/scidavis/files/1320894/use-gsl-vectors-in-trapezoid.patch.txt)

**Comment by highperformancecoder** [comment]
Why is this an improvement?

**Comment by gbm19** [comment]
Because I believe gsl library is exception safe (I can be wrong). 
Even if it is not, gsl was already used in Integration.cpp, so if in the future gsl is replaced by something better, it will also be replaced in trapezoid().

**Comment by gbm19** [comment]
Maybe you  prefer this
[use-std-vector-in-trapezoid.patch.txt](https://github.com/highperformancecoder/scidavis/files/1323955/use-std-vector-in-trapezoid.patch.txt)

**Comment by highperformancecoder** [comment]
On Fri, Sep 22, 2017 at 08:52:55AM +0000, gbm19 wrote:
> Maybe you  prefer this
> [use-std-vector-in-trapezoid.patch.txt](https://github.com/highperformancecoder/scidavis/files/1323955/use-std-vector-in-trapezoid.patch.txt)
> 
> 
> -- 
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub:
> https://github.com/highperformancecoder/scidavis/pull/54#issuecomment-331390485

<professor mode on>
Yes, that version is RAII, the GSL version is not. Did you look up the
concept of RAII and the issue of exception safety? RAII also makes it
very difficult to code memory leaks.

BTW GSL is a C language API, so has no inbuilt concept of exceptions,
let alone exception safety. Were you confusing it with thread safety?
</professor mode off>

Cheers
-- 

----------------------------------------------------------------------------
Dr Russell Standish                    Phone 0425 253119 (mobile)
Principal, High Performance Coders
Visiting Senior Research Fellow        hpcoder@hpcoders.com.au
Economics, Kingston University         http://www.hpcoders.com.au
----------------------------------------------------------------------------

**Comment by gbm19** [comment]
Well, I was mislead by a too quick look at the results of googling gsl+RAII.
Thanks for clarifying.
Please, apply the vector version patch.

**Comment by highperformancecoder** [comment]
On Fri, Sep 22, 2017 at 12:18:56PM +0000, gbm19 wrote:
> Well, I was mislead by a too quick look at the results of googling gsl+RAII.
> Thanks for clarifying.
> Please, apply the vector version patch.


Sure, well will do. Of course, I could always do that, but code review
does give educational opportunities too.

RAII is probably the most important C++ concept. After that, const
correctness is also very important. SciDaVis has been mostly written
without cognizance of these basic principles, so there's a lot of work
to bring the codebase up to spec.


-- 

----------------------------------------------------------------------------
Dr Russell Standish                    Phone 0425 253119 (mobile)
Principal, High Performance Coders
Visiting Senior Research Fellow        hpcoder@hpcoders.com.au
Economics, Kingston University         http://www.hpcoders.com.au
----------------------------------------------------------------------------

**Pull request merged**
