### PR TITLE
Adapt qmake project files to system-wide liborigin library

### PR DESCRIPTION
**Pull request by gbm19**

### CODE REVIEW

**Comment by highperformancecoder** [comment]
So in reading this code, does liborigin use pkg-config? I installed liborigin-devel on Tumbleweed, but pkg-config doesn't know about it. This is the relevant info:

Information for package liborigin-devel:
----------------------------------------
Repository     : openSUSE-20180515-0                     
Name           : liborigin-devel                         
Version        : 2.0.0-1.2                               
Arch           : x86_64                                  
Vendor         : openSUSE                                
Installed Size : 109.6 KiB                               
Installed      : Yes                                     
Status         : up-to-date                              
Source package : liborigin-2.0.0-1.2.src                 
Summary        : Libraries and header files for liborigin
Description    :                                         
    This package contains libraries and header files for developing
    applications that read OriginLab OPJ project files.

**Comment by gbm19** [comment]
Sorry, it is my fault. It had to be more explicit and give instructions to install liborigin 3.0.0 either from git repo at sourceforge or from code in SciDAVis.
See attachment.
[install-liborigin-instructions.txt](https://github.com/highperformancecoder/scidavis/files/2447666/install-liborigin-instructions.txt)

**Comment by highperformancecoder** [comment]
On Thu, Oct 04, 2018 at 06:39:03PM +0000, gbm19 wrote:
> Sorry, it is my fault. It had to be more explicit and give instructions to
> install liborigin 3.0.0 either from git repo at sourceforge or from code in
> SciDAVis.
> See attachment.
> install-liborigin-instructions.txt

OK - ultimately, I would assume you plan to do releases of liborigin
3.x, and at that point, I would hope to eliminate the scidavis vendor
branch altogether.

In the meantime, it might be worth setting up liborigin as a submodule
of scidavis - this will allow automated synchronisation of the
scidavis and liborigin repos. If you like, since I have done
submodules before, I could take a crack, and see if you like it.

-- 

----------------------------------------------------------------------------
Dr Russell Standish                    Phone 0425 253119 (mobile)
Principal, High Performance Coders
Visiting Senior Research Fellow        hpcoder@hpcoders.com.au
Economics, Kingston University         http://www.hpcoders.com.au
----------------------------------------------------------------------------

**Comment by gbm19** [comment]
Missatge de Russell Standish <notifications@github.com> del dia dv., 5
d’oct. 2018 a les 13:45:

> OK - ultimately, I would assume you plan to do releases of liborigin
> 3.x, and at that point, I would hope to eliminate the scidavis vendor
> branch altogether.
>

Yes.


> In the meantime, it might be worth setting up liborigin as a submodule
> of scidavis - this will allow automated synchronisation of the
> scidavis and liborigin repos. If you like, since I have done
> submodules before, I could take a crack, and see if you like it.
>

I am not sure it is worth the effort.
I do not expect any large or continuous changes in liborigin now that
the (only) two projects that use it have normalized its use.
This PR (#101) is just the outcome of testing if the pkg-config file in
liborigin was correct

**Comment by highperformancecoder** [comment]
On Fri, Oct 05, 2018 at 03:30:43PM -0700, gbm19 wrote:
> > In the meantime, it might be worth setting up liborigin as a submodule
> > of scidavis - this will allow automated synchronisation of the
> > scidavis and liborigin repos. If you like, since I have done
> > submodules before, I could take a crack, and see if you like it.
> >
> 
> I am not sure it is worth the effort.
> I do not expect any large or continuous changes in liborigin now that
> the (only) two projects that use it have normalized its use.
> This PR (#101) is just the outcome of testing if the pkg-config file in
> liborigin was correct

Fair enough. This can be pushed to SciDaVis 2.x, by which time
liborigin 3.x should be released.


-- 

----------------------------------------------------------------------------
Dr Russell Standish                    Phone 0425 253119 (mobile)
Principal, High Performance Coders
Visiting Senior Research Fellow        hpcoder@hpcoders.com.au
Economics, Kingston University         http://www.hpcoders.com.au
----------------------------------------------------------------------------

**Pull request merged**
