### PR TITLE
Update scidavis.appdata.xml

### PR DESCRIPTION
**Pull request by kevinsmia1939**
I found this while building SciDAVis for Flatpak
Use SPDX for project license.
Add release.
Add content rating.

### CODE REVIEW

**Comment by kevinsmia1939** [comment]
I don't know when will 2.4.0 be release, so I just put for 2.3.0

**Comment by highperformancecoder** [comment]
Hi Kevin, What would be great is if you could modify the makeRelease.sh script to automatically update this file whenever the release version is bumped. I hope you're slightly au fait with bourne shell scripting.

**Comment by kevinsmia1939** [comment]
Never do bash scripting in my life, but I will look into it.

**Comment by kevinsmia1939** [comment]
@highperformancecoder 
BTW, I manage to build SciDAVis for Flatpak now, when the new version release with cmake I will submit it.

**Pull request merged**
