### PR TITLE
Use initializer list for class data member initialization

### PR DESCRIPTION
**Pull request by narunlifescience**
1) removed init() function & added its contents to the constructor as initializer list for better class member initialization.. 
2) rename initGlobalConstants() to initFonts() & move member variables to initializer list

### CODE REVIEW

**Comment by highperformancecoder** [comment]
Accepted pull request. I ended up comparing the deletions and additions in two edit windows, satisfying myself this was a valid refactor.

**Comment by narunlifescience** [comment]
Thanks for the effort... I see a lot of issues with scidavis code. I would like to help in whichever manner possible to make it better.. is there any specific part you would like me to work on ?

**Comment by highperformancecoder** [comment]
On Sun, Jan 24, 2016 at 04:31:49AM -0800, Arun Narayanankutty wrote:

> Thanks for the effort... I see a lot of issues with scidavis code. I would like to help in whichever manner possible to make it better.. is there any specific part you would like me to work on ? 

I know what you mean. It is a classic example of a "ball of mud".

My approach has been to tackle the logged tickets, in roughly the
order of priority. I think I've managed to close all fatal, critical
and urgent bugs prior to the last release, leaving anything at normal
level or lower to be done.

Other tasks:

1) Write more unit tests. Refactoring efforts are rather hamstrung
until this is done. This is going to be hard, so I'd suggest just
picking an area for refactoring, and writing unit tests as an initial
step of the refactor to try to cover what needs to be touched.

2) Updating to more modern libraries, such as qwt6 and qt5. I have
made a start with qwt6, but the "ball of mud" ended up defeating me. I
need to start again, with lessons learnt, by writing a small amount of
shim code to handle the mind bogglingly stupid API decisions made for qwt6.

3) Getting rid of qt assistant, and moving the manual (such as it is)
into an HTML tree such that scidavis can run a broswer in a context
sensitive way. The sort of thing I have in mind is implemented in the
Minsky project.

These are my ideas. Obviously, as a volunteer, we got to do what
scratches our interest, and a lot of that stuff is pretty unglamorous.

What do you think?

## 

---

Dr Russell Standish                    Phone 0425 253119 (mobile)
Principal, High Performance Coders
Visiting Senior Research Fellow        hpcoder@hpcoders.com.au

## Economics, Kingston University         http://www.hpcoders.com.au

**Comment by highperformancecoder** [comment]
Oh - and I should also mention one other task - getting Python to
build with MXE (or even to play nice) such that we can include Python
scripting with the Windows build.

Cheers

## 

---

Dr Russell Standish                    Phone 0425 253119 (mobile)
Principal, High Performance Coders
Visiting Senior Research Fellow        hpcoder@hpcoders.com.au

## Economics, Kingston University         http://www.hpcoders.com.au

**Comment by narunlifescience** [comment]
I think I could start with qt5 port for now as it would make me familiar with scidavis code. I will also have a look in to Minsky project to deal with qtAssistant. I would surely stumble up on some bugs while porting the code.  
The source code is really hard to read without formatting.. I would suggest google style formatting(if you don't have any other suggestions).  Also we should stick to one variable per line declaration(atleast for class members) to follow the order of member initiation & readability. 
Another thing would be unused variable declarations. we could just comment them out for now to suppress overwhelming compiler warnings.
what is your opinion on this?

**Comment by highperformancecoder** [comment]
On Sun, Jan 24, 2016 at 05:32:19PM -0800, Arun Narayanankutty wrote:

> I think I could start with qt5 port for now as it would make me familiar with scidavis code. I will also have a look in to Minsky project to deal with qtAssistant. I would surely stumble up on some bugs while porting the code.  
> 
> The source code is really hard to read without formatting.. I would
> suggest google style formatting(if you don't have any other
> suggestions).  

I would not be too hung up on mandating formatting standards. But feel
free to reflow (ie "pretty print") the source code in the text editor
of your choice to make the code more readable. For reference, my own
personal choice is spaces (not tabs) with 2 space indentation. But,
probably like you, I work on multiple different projects, and I can't
set up per project preferences for this sort of thing, so just tend
to stick with whatever the file already has, unless it is too gnarly,
in which can I just reflow the code.

Also we should stick to one variable per line declaration(atleast for class members) to follow the order of member initiation & readability. 

> Another thing would be unused variable declarations. we could just
> comment them out for now to suppress overwhelming compiler warnings.

Sure, or delete 'em entirely. Member initialisation should occur in
declaration order if possible (best practise), but the compiler now tends to
create a warning anyway if this rule is abrogated.

As for one variable per line - I'm happy either way. If its a bunch of
undocumented temporary or local variables, then I see no harm in
having multiple on a line. Obviously documented, and more signicant
variables ought to live on their own line to make them easier to find.

> what is your opinion on this?

Obviously getting rid of warnings is a useful code cleanup task to do,
but not necessarily highest priority.

If possible, though, could you separate pull requests containing
non-functional changes (eg pretty printing, or warning removals) from
actual bug fixes, it will help me in reviewing the change. I think you
might be doing this anyway, in that you've mostly been sending me lots
of small pull requests.

Cheers

## 

---

Dr Russell Standish                    Phone 0425 253119 (mobile)
Principal, High Performance Coders
Visiting Senior Research Fellow        hpcoder@hpcoders.com.au

## Economics, Kingston University         http://www.hpcoders.com.au

**Comment by narunlifescience** [comment]
Thanks!

**Pull request merged**
